header:
  version: 15

distro: poky

repos:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    tag: yocto-5.0.18
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: scarthgap
    commit: b0c2c648a1af89e7a8dd4c2ec841f3bc0ed0ccb9
    layers:
      meta-oe:
      meta-networking:
      meta-python:
      meta-perl:

  meta-linux-mainline:
    url: https://github.com/betafive/meta-linux-mainline
    path: layers/meta-linux-mainline
    branch: scarthgap

  meta-caching:
    path: meta-caching

local_conf_header:
  00_base: |
    CONF_VERSION = "2"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    CORE_IMAGE_EXTRA_INSTALL:append = " efivar nano"
    INIT_MANAGER = "systemd"
    ENABLE_BINARY_LOCALE_GENERATION = "1"
    GLIBC_GENERATE_LOCALES:append = " en_GB.UTF-8 en_US.UTF-8"
    IMAGE_LINGUAS ?= "en-gb"
  01_kernel: |
    require conf/linux-mainline/stable.inc
    PREFERRED_VERSION_linux-stable = "7.1%"
