header:
  version: 15

distro: poky

repos:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    branch: scarthgap
#    commit: e139e9d0ce343ba77a09601a976c92acd562c9df
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: scarthgap
#    commit: 8e297cdc841c6cad34097f00a6903ba25edfc153
    layers:
      meta-oe:
      meta-networking:
      meta-python:
      meta-perl:

  meta-caching:
    path: meta-caching

local_conf_header:
  00_base: |
    CONF_VERSION = "2"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    CORE_IMAGE_EXTRA_INSTALL:append = " efivar"
