header:
  version: 15

distro: poky

repos:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    branch: scarthgap
    commit: 72983ac391008ebceb45edc7a8f0f6d5f4fe715c
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: scarthgap
    commit: ec0469748be4159fb83fb0fa0148d786484c88cf
    layers:
      meta-oe:
      meta-networking:
      meta-python:
      meta-perl:

  meta-caching:
    path: meta-caching

local_conf_header:
  00_base: |
    CONF_VERSION = "2"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    CORE_IMAGE_EXTRA_INSTALL:append = " efivar nano"
    INIT_MANAGER = "systemd"
    PREFERRED_PROVIDER_virtual/kernel = "linux-mainline"
    ENABLE_BINARY_LOCALE_GENERATION = "1"
    GLIBC_GENERATE_LOCALES:append = " en_GB.UTF-8 en_US.UTF-8"
    IMAGE_LINGUAS ?= "en-gb"

